spring.application.name: customer_service

instance.id: ${random.value}

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
     instanceId: ${instance.id}

server.port: 8080
management.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/c7_data_customer
    username: c7
    password: c7

management.security.enabled: false