zuul:
  #prefix: /api
  routes:
    customer:
      path: /customer/**
      serviceId: CUSTOMER
      retryable: true

spring:
  application:
    name: zuul

management.security.enabled: false
security.basic.enabled: false
hystrix.command.default.execution.timeout.enabled: false

management.endpoints.web.exposure.include: "*"